### ISSUE TITLE
アップロードファイルをファイル種別ごとに整理

### ISSUE THREAD

**Issue by tsunekawa** [code4lib-japan/code4lib-japan.github.io#10]
移行したアップロードファイルをファイルの種類ごとに整理する（現在はすべて /assets/images/ 以下に入っている )。

**Comment by yegusa** [comment]
/assets/images　というフォルダは見当たりません　/assets/uplaods はあるけど。

**Comment by tsunekawa** [comment]
すみません、実態と合わせるために 5cc63 で /assets/images から /assets/uploads に変更しました。

**Comment by yegusa** [comment]
imagesってフォルダ名だとあれだけど、uploads ってフォルダ名なら、種別ごとに整理する必要なさそうに思うのだけど、なんか、別の趣旨で必要なことがあるんでしょうか？

**Comment by tsunekawa** [comment]
そうですね、たしかに uploads であれば特に必要はないですね。では、この issue はクローズにしたいと思います。ありがとうございました。
