### ISSUE TITLE
READMEを書きなおす

### ISSUE THREAD

**Issue by tsunekawa** [code4lib-japan/code4lib-japan.github.io#4]
* ローカル環境下でプレビューする方法
* このリポジトリの概要
* ライセンスの説明
* コントリビュートの仕方

などをREADMEに書いておきたい。

**Comment by masao** [comment]
## このリポジトリについて

このリポジトリは Code4Lib JAPAN の公式サイト code4lib.jp の再構築のためのリポジトリです。

変更すべき点や気になる箇所を見つけた方は、 Issue や Pull request によりご報告いただければ幸いです。

サイト全体を Github Pages により構成していますので、ローカル環境でサイト内容をプレビュー確認されたい方は [Jekyll](https://jekyllrb.com)（[日本語訳サイト](https://jekyllrb-ja.github.io/)）をお試しください。

----

## About this repository

This repository is a on-going project for rebuilding the official web site of Code4Lib JAPAN.

Please feel free to use Issue or Pull request, if you find any issues or problems.

This site is built on top of Github Pages. You can preview its contents with [Jekyll](https://jekyllrb.com).

**Comment by masao** [comment]
こんな感じで。ライセンスは特に定めてなかったと思うのでちょっと保留。
CC-BYでよさそうな気はするが。。。

**Comment by tsunekawa** [comment]
ありがとうございます！こちらをREADMEに反映させます。ローカルでのプレビューはDockerにも対応しているのですが、それは後ほど追記しますね。
