### ISSUE TITLE
https://www.code4lib.jp/about/ のリンク切れ解決

### ISSUE THREAD

**Issue by kiyota-yoji** [code4lib-japan/code4lib-japan.github.io#52]
https://www.code4lib.jp/about-2/ にリダイレクトさせる

**Comment by tsunekawa** [comment]
マージしましたが、リンク切れは解決しないみたいです。
https://www.code4lib.jp/about/

**Comment by kiyota-yoji** [comment]
@tsunekawa 
確認ありがとうございます。
おそらく原因はこれですね。

https://github.com/jekyll/jekyll-redirect-from
> If you're using Jekyll in safe mode to mimic GitHub Pages, make sure to add jekyll-redirect-from to your whitelist:
> whitelist:
>   - jekyll-redirect-from

というわけで、whitelistに追加します。

**Comment by tsunekawa** [comment]
ご対応ありがとうございます。マージしました。

**Comment by kiyota-yoji** [comment]
解決したことを確認しました。
