### ISSUE TITLE
人工知能学会誌の著者最終版削除、問い合わせベースでのご提供に変更

### ISSUE THREAD

**Issue by kiyota-yoji** [code4lib-japan/code4lib-japan.github.io#63]

**Comment by tsunekawa** [comment]
著者最終版のPDFを全コミットから削除しました。 .gitignoreにも対象ファイルを追加し、誤記載を防ぐように対処しました。

c93f503ab4fc21cd1410f64af916bc2a44fba517

この対応によってコミットログの改変が行われているため、フォークしているリポジトリは削除のうえ再フォークする必要があります。
