### ISSUE TITLE
about-2 の肩書修正

### ISSUE THREAD

**Issue by yegusa** [code4lib-japan/code4lib-japan.github.io#85]
https://www.code4lib.jp/about-2/

修正必要かどうかも不明。

- [x] OK 江草 由佳（国立教育政策研究所）※共同代表
- [x] OK 岡本 真（アカデミック・リソース・ガイド株式会社、NPO法人横浜コミュニティデザイン・ラボ）※事務局長
- [ ] 要修正：筑波大学　小野 永貴（日本大学）
- [ ] 要修正：東京大学 小野 亘（国立情報学研究所）
- [ ] たぶんOK 川嶋 斉（野田市立興風図書館）
- [ ] たぶんOK 清田 陽司（株式会社LIFULL AI戦略室、株式会社メディンプル）※共同代表
- [x] OK 阪口 哲男（筑波大学）
- [x] OK 高久 雅生（筑波大学）
- [x] OK 常川 真央（中央大学）※共同代表
- [ ] たぶんOK林 賢紀（国際農林水産業研究センター）
- [ ]  要修正：山中湖情報創造館、八ヶ岳コモンズ、NPO法人地域資料デジタル化研究会　丸山 高弘（山中湖情報創造館、NPO法人地域資料デジタル化研究会）
- [ ] 要修正 米田 渉（成田市役所）

**Comment by otani0083** [comment]
小野さんは、国立情報学研究所から東京大学へ所属変わられています。

**Comment by yegusa** [comment]
@otani0083 さん、ありがとございます。

**Comment by yegusa** [comment]
現在、本人に確認中です。

**Comment by yegusa** [comment]
修正完了しましたので、クローズします。
